name: Manager build workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup gradle
      run: chmod +x gradlew
    - name: Build the package
      run: ./gradlew build
    - name: Upload the package
      uses: actions/upload-artifact@v1
      with:
        name: Manager
        path: app/build/outputs/apk/debug/app-debug.apk 
